### ISSUE TITLE
when i put this scripts into the .txt file named weapons it doesnt work

### ISSUE THREAD

**Issue by MUNKEE323** [XxpichoclesxX/GtaVScripts#24]
i personaly dont know how to script so i am basically assking for hel,p please i want to be able rto boot the assholes who torture other modders fort no reason

**Comment by L7NEG** [comment]
If you are using kiddions menu go to kiddions scripts folder and put the .lua file only in it

**Comment by MUNKEE323** [comment]
ok

**Comment by MUNKEE323** [comment]
how do i use the boot scripts

**Comment by XxpichoclesxX** [comment]
Should be fixed
