### ISSUE TITLE
Malicious Features

### ISSUE THREAD

**Issue by XxpichoclesxX** [XxpichoclesxX/GtaVScripts#8]
# All Malicious Done by now

- Script Crash V1
- Script Crash V2
- Script Crash V3
- Script Crash V4

# Later 
- Low Range Crash From 2take1
- Far Range Crash From 2take1
- AIO Crash From 2take1

**Comment by XxpichoclesxX** [comment]
Need some help Passing 2take1 Menu nativos to stand natives

**Comment by DeathRowKingPin007** [comment]
That's not right

**Comment by DeathRowKingPin007** [comment]
Won't work and that's not right!!! That's why they wrote not to transferred to other menus

**Comment by DeathRowKingPin007** [comment]
That's not right !! They're paid menus and that theft of services and one reason they wrote it not to transferable

**Comment by DeathRowKingPin007** [comment]
Why delete my comment
